name: Run monolithic experiments
on:
  push:
    branches:
      - introduce-ci

jobs:
  run_experiments:
    strategy:
      matrix:
        experiment:
        - name: Newmark_beta
          args: '-tss Newmark_beta -w 10 -o convergence-studies/monolithic_Newmark_beta.csv'
        - name: generalized_alpha
          args: '-tss generalized_alpha -w 10 -o convergence-studies/monolithic_generalized_alpha.csv'
        - name: runge_kutta_4
          args: '-tss runge_kutta_4 -w 10 -o convergence-studies/monolithic_runge_kutta_4.csv'
        - name: radauIIA
          args: '-tss radauIIA -w 10 -o convergence-studies/monolithic_radauIIA.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./monolithic
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt install -y python3-venv
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate venv
        # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          python3 doConvergenceStudy.py --silent --executor Github ${{ matrix.experiment.args }}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: monolithic ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./monolithic/convergence-studies
  merge:
    runs-on: ubuntu-latest
    needs: run_experiments
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: monolithic
