name: Run precice-2 experiments
on:
  push:
    branches:
      - introduce-ci

jobs:
  run_experiments:
    strategy:
      matrix:
        experiment:
        - name: Higher-order time stepping Newmark_beta
          args: '-tss Newmark_beta Newmark_beta -o convergence-studies/higher-order/precice_2_Newmark_beta.csv'
        - name: Higher-order time stepping generalized_alpha
          args: '-tss generalized_alpha generalized_alpha -o convergence-studies/higher-order/precice_2_generalized_alpha.csv'
        - name: Higher-order time stepping runge_kutta_4
          args: '-tss runge_kutta_4 runge_kutta_4 -o convergence-studies/higher-order/precice_2_runge_kutta_4.csv'
        - name: Higher-order time stepping radauIIA
          args: '-tss radauIIA radauIIA -o convergence-studies/higher-order/precice_2_radauIIA.csv'
        - name: Subcycling Newmark_beta
          args: '-s 5 -sb 1 1 -sf 2 1 -w 1 -tss Newmark_beta Newmark_beta -o convergence-studies/subcycling/precice_2_Newmark_beta.csv'
        - name: Subcycling generalized_alpha
          args: '-s 5 -sb 1 1 -sf 2 1 -w 1 -tss generalized_alpha generalized_alpha -o convergence-studies/subcycling/precice_2_generalized_alpha.csv'
        - name: Subcycling runge_kutta_4
          args: '-s 5 -sb 1 1 -sf 2 1 -w 1 -tss runge_kutta_4 runge_kutta_4 -o convergence-studies/subcycling/precice_2_runge_kutta_4.csv'
        - name: Subcycling radauIIA
          args: '-s 5 -sb 1 1 -sf 2 1 -w 1 -tss radauIIA radauIIA -o convergence-studies/subcycling/precice_2_radauIIA.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./precice-2
    container: precice/precice:2.5.1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3.12-venv
          rm -rf /var/lib/apt/lists/*
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate venv
        # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          python3 doConvergenceStudy.py precice-config-template.xml --silent --executor Github ${{ matrix.experiment.args }}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: precice-2 ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./precice-2/convergence-studies
  merge:
    runs-on: ubuntu-latest
    needs: run_experiments
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: precice-2
